### PR TITLE
Update plugin to be in sync with latest stable deluge 1.3 version (1.3.12)

### PR DESCRIPTION
**Pull request by h3llrais3r**
Thanks to @kingamajick for initial version.
Now updated with latest version of 1.3-stable scheduler plugin (1.3.12).

### CODE REVIEW

**Comment by h3llrais3r** [comment]
You can also merge the other pull request (PR https://github.com/jamielennox/deluge-myscheduler/pull/1) because @kingamajick already merged my changes into his branch.

**Comment by jamielennox** [comment]
Hi @h3llrais3r and @kingamajick - thanks for your interest in this.

Unfortunately i no longer run deluge on any of my boxes so i really don't have a good way to test this out. I'm happy the plugin lives on though. If one of you would like to be the owner for this I'll happily update my readme to say this is deprecated and point to your new repository.

Let me know which repository you'd like it to be.

**Comment by h3llrais3r** [comment]
Hi @jamielennox.
I've already contacted @kingamajick and he is also not longer using the plugin.
So you can point to my repository if you want.

**Comment by kingamajick** [comment]
Yep, I'm no longer using this plugin, so it would be best to point to @h3llrais3r repo :)

**Comment by jamielennox** [comment]
@h3llrais3r I can transfer the repository to you, that way anything currently pointing to my repo should just redirect to you and you can keep the pull requests. However you have to move your existing repo. https://help.github.com/articles/transferring-a-repository/

**Comment by jamielennox** [comment]
Otherwise i've just put up a quick readme that points people over.

**Comment by h3llrais3r** [comment]
I've just renamed my fork. Is this sufficient or do I really need to delete it first?

**Comment by jamielennox** [comment]
it appears you need to actually remove it: 

 h3llrais3r already has a repository in the jamielennox/deluge-myscheduler network

**Comment by h3llrais3r** [comment]
I've now deleted the fork.

**Comment by h3llrais3r** [comment]
Transfer accepted! :+1:

**Pull request merged**
